security:
    enable_authenticator_manager: true
    password_hashers:
        Symfony\Component\Security\Core\User\UserInterface:
            algorithm: auto

    # Configuration du fournisseur d'utilisateurs
    providers:
        app_user_provider:
            id: App\Security\UserProvider

    # Configuration des pare-feu
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            provider: app_user_provider
            custom_authenticator: App\Security\UserAuthenticator
            logout:
                path: app_logout
                # where to redirect after logout
                # target: app_any_route

            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800
                path: /
                always_remember_me: true

            # activate different ways to authenticate
            # https://symfony.com/doc/current/security.html#the-firewall

            # https://symfony.com/doc/current/security/impersonating_user.html
            # switch_user: true

    # Contrôle d'accès
    access_control:
        # - { path: ^/admin, roles: ROLE_ADMIN }
        # - { path: ^/profile, roles: ROLE_USER }

# Configuration du hachage de mot de passe pour les tests
when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\UserInterface:
                App\Entity\User:
                    algorithm: auto